### ISSUE TITLE
Email verification stuck in "pending"

### ISSUE THREAD

**Issue by tobilg** [medmunds/aws-cfn-ses-domain#14] opened 2020-10-15 22:04 UTC
## Summary
Email verification is stuck in "pending". Unfortunately, there's no log output. How can this be debugged?

## Steps to reproduce
Deployed according to the README

**Comment by medmunds** [comment] 2020-10-16 01:09
> How can this be debugged?

From the information you've provided, it can't.

I'd be happy to help you try to figure out what might be going wrong, if you'd be willing to put in a little effort to explain what you're trying to do, how you're trying to do it, and the results you're seeing. (Are you trying to verify an EmailIdentity or an email Domain? What are the relevant parts of your CloudFormation template? What's the status of the SES resource(s) in the CloudFormation console, and are there any failure events shown? Does every SES resource you to provision get stuck, or just certain ones? What version of aws-cfn-ses-domain are you using? Etc.)

(Just to double check one likely problem: if you're trying to provision a `Custom::SES_EmailIdentity`, did you receive the Amazon SES verification email? Did you click the link in it?)

**Comment by tobilg** [comment] 2020-10-16 07:38
Hi! Thanks for your fast reply! I'm using the latest version, but integrated the resources in my existing stack. It deploys fine, but to me it's kind of unclear what additional settings/resources I need to add so that I can actually receive the confirmation email.

I have added an email identity for my route53 domain (e.g. tobi@mydomain.com), and that's where I'm stuck now. I'm aware that we can have a SNS Topic and SES Rules/RuleSet to forward the incoming mails, but apparently I misconfigured something downstream.

So how does one actually use the email identities, provided that I not just want to send emails, but also receive emails?

Thanks a lot for your help!

By the way, the email identities setup only worked one I added the `ses:VerifyEmailIdentity` action to the `CustomDomainLambdaExecutionRole`, and logs could only be written if the managed policy `arn:aws:iam::aws:policy/service-role/AWSLambdaRole` was referenced.

**Comment by tobilg** [comment] 2020-10-16 12:08
I managed to change to LOG_LEVEL to INFO, and now I see the following:

```
[INFO]	2020-10-16T07:30:21.410Z	408d9033-6127-40e9-aa3d-65e0c0abec41	SES:VerifyEmailIdentity(EmailAddress='tobi@mydomain.com') => {'ResponseMetadata': {'RequestId': 'f568877f-b5e4-4951-901f-488747bdc0c7', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f568877f-b5e4-4951-901f-488747bdc0c7', 'content-type': 'text/xml', 'content-length': '248', 'date': 'Fri, 16 Oct 2020 07:30:20 GMT'}, 'RetryAttempts': 0}}
```

In the SES UI in the Console, the email identity is still shown as "pending" though... Any ideas?

**Comment by medmunds** [comment] 2020-10-16 19:11
OK, so if I understand correctly, you are trying to verify both a domain you control (mydomain.com) and an individual email in that domain (tobi​@mydomain.com) for sending through SES?

You don't need to do both. Once you verify a sending domain, SES allows sending from every email in that domain without further verification. See [*Verifying domains in Amazon SES*](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-domains.html) in the AWS docs. 

One general suggestion from my own experience getting started with SES: at first, it's a good idea to get SES working entirely through the AWS SES console. The console includes a lot of helpful info (and often links to the docs) about some weird things in SES that might not be obvious if you're just calling the APIs through CloudFormation. Once you get everything working the way you want through the console, *then* tear it down and create a CF template that automates the same configuration. (Also, before you try to send email elsewhere, make sure you understand the [SES sandbox](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html).)

A couple other things:

> the email identities setup only worked one I added the `ses:VerifyEmailIdentity` action to the `CustomDomainLambdaExecutionRole`, and logs could only be written if the managed policy `arn:aws:iam::aws:policy/service-role/AWSLambdaRole` was referenced

Both of these are [already included](https://github.com/medmunds/aws-cfn-ses-domain/blob/v0.3/aws-cfn-ses-domain.cf.yaml#L84-L97) in the Custom*Email*LambdaExecutionRole this package sets up for `Custom::SES_EmailIdentity`. (And logging is also included in Custom*Domain*LambdaExecutionRole, along with other permissions needed for `Custom::SES_Domain`.) 

It seems like you may have made some unintended changes in the code. (That's why you're encouraged to include your CF template in issue reports here.) It's probably easiest to run aws-cfn-ses-domain as a nested stack as shown in the readme, rather than copying bits and pieces of it into your own template.

> I managed to change to LOG_LEVEL to INFO, and now I see the following: ... `SES:VerifyEmailIdentity(EmailAddress='tobi@mydomain.com') => ... 'HTTPStatusCode': 200 ...`
In the SES UI in the Console, the email identity is still shown as "pending" though...

That's a successful (status 200) call to `SES:VerifyEmailIdentity`. We've asked SES to send a verification email to tobi​@mydomain.com, and SES has agreed it will send that email. (BTW, if this call hadn't succeeded, the CloudFormation console would show a failure event for this resource, no extra logging required. That's why I asked what the CF console showed for your SES resources.)

But "success" just means SES will try to send the verification email. It doesn't mean it's been delivered, or that you've opened it and clicked the verification link. Until you do that, SES correctly considers the email identity to be "pending" (see [*Verifying email addresses in Amazon SES*](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses.html) in the AWS docs). So if there's any question about you being able to *receive* email (in general) sent to tobi​@mydomain.com, you need to get that working first before trying to verify it as an SES *sender.*

Again, though, if you are verifying mydomain.com as an SES sending domain, you *don't* need to also verify tobi​@mydomain.com as an individual sending address.

**Comment by tobilg** [comment] 2020-10-20 20:12
Thanks again for the very comprehensive answer, really appreciated! Honestly, I'm quite confused about SES. I was trying to use a custom domain and email identity to be able to send emails from Cognito events (see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-email-address-customization.html and https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-ses-authorization-to-send-email.html) for example. Both of these links talk about email identities, so I assume I need to verify them first.

Which is, in this case, a deadlock, because I cannot (yet) receive emails on the respective identities. It's a bit like Schroedingers email identity, it's there but it's not.

Do you have any idea eventually how to solve this? Thanks again in advance!

**Comment by medmunds** [comment] 2020-10-22 19:16
Yeah, SES uses a bunch of terminology that seems like it was designed just to cause confusion.

There are two kinds of [*SES identities*](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html) that you can use to send email from SES. With either, you have to prove you control the identity before SES will let you send from it:

* An SES *domain identity* allows you to send email from *any* email address at a domain you control. For example, if you own mydomain.com, you could send email from tobi​@mydomain.com or help​@mydomain.com or noreply​@mydomain.com or whatever. You verify a domain identity (prove you control the domain) by creating certain DNS records that SES specifies.

* An SES *email identity* allows you to send email from a specific email address, typically at a domain you *don't* control. For example, tobi​@gmail.com or tobi​@big-corporate-employer.com. You verify an email identity (prove you control that one email address) by clicking a link in a challenge email that SES sends to it.

When the Cognito docs say you can use an "Amazon Simple Email Service identity," I believe they're referring to either kind of *SES* identity. So if you want to send from tobi​@mydomain.com, you only need to verify the mydomain.com *SES domain identity* by adding the required DNS records. It doesn't matter whether or not you can receive email there. (Again, this all assumes you own mydomain.com.)

But I've never worked with Cognito. If the suggestion to use an SES domain identity doesn't help, I'd maybe try asking in the AWS Support Forums or somewhere that has some Cognito users.

In any case, this doesn't seem like a bug in aws-cfn-ses-domain, so I'm going to close this issue.

**Closed as completed by medmunds** 2020-10-22 19:16 UTC
